---
--- Generated by PluginCreator
--- game_business entity
--- DateTime:2023-04-10
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
