---
--- Generated by PluginCreator
--- timelight entity_common
--- DateTime:2021-11-04
---

local ValueDef = T(Entity, "ValueDef")
-- key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
--ValueDef.xxx 					= {false,   false,  true,   false,      0,                      true}
local Entity = Entity
