---
--- Generated by PluginCreator
--- camera_edit gm
--- DateTime:2023-05-25
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
GMItem["General Role/Camera Scheduling Mode"] = function()
    UI:openWindow("UI/gm/gui/camera_edit")
end
GMItem["Role General/Scene Welcome Screen"] = function()
    Me:showWelcome("map_muye")
end
--GMItem["角色通用/镜头调度模式"] = GM:inputNumber(function(self, pos)
--    UI:openWindow("UI/gm/gui/camera_edit")
--    --Me:setActorHide(true)
--	--Me:setFlyMode(1)
--    --Blockman.instance:setPersonView(0)
--    --Blockman.instance:setPersonView(tonumber(pos))
--    --Me:changeCameraView(Lib.v3(Me:getPosition().x, Me:getPosition().y, Me:getPosition().z), Me:getRotationYaw(),Me:getRotationPitch() ,10)
--    --print("Me.sourceCameraPos:"..Lib.v2s(Camera.getActiveCamera():getPosition()))
--    --print("Me.getPosition:"..Lib.v2s(Me:getPosition()))
--end)

