---
--- Generated by PluginCreator
--- game_time 's gate
--- DateTime:2021-11-26
--- @class GameTimeServer
local GameTimeServer = T(Lib, "GameTimeServer")
--function GameTimeServer:export_getXXX()
	-----TODO
--end

--function GameTimeServer:import_getXXX()
	-----TODO
--end
return GameTimeServer
