---
--- Generated by PluginCreator
--- game_time gm
--- DateTime:2021-11-26
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

---@type GameTimes
local GameTimes = T(Lib, "GameTimes")

GMItem["time/modify time"] = GM:inputStr(function(self, var)
    local time = Lib.splitString(var or "", ":", true)
    GameTimes:setTime(time[1] or 12,time[2] or 0)
    end, function()
        return string.format("%d:%d", 12, 0)
    end
)
