---
--- Generated by PluginCreator
--- game_mission entity
--- DateTime:2023-06-14
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
