---
--- Generated by PluginCreator
--- scene_object entity_func
--- DateTime:2023-03-23
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
--function Entity.ValueFunc:xxx(value)
--    Lib.emitEvent(Event.xxx,1,value)
--end
