---
--- Generated by PluginCreator
--- scene_object entity
--- DateTime:2023-03-23
---

local Entity = Entity

--- 传送至指定地图的坐标位置
---@param mapName string
---@param position Vector3 为空则默认出生点
---@param finish function 传送完毕回调，传入参数是否成功
---@param setBorn boolean 是否设置为出生地图
---@return boolean 是否成功触发传送
function Entity:teleportToMapPosition(mapName, position, finish, setBorn)
    ---@type Entity
    local entity = self
    if entity:isInStateType(Define.RoleStatus.IN_TELEPORT) or entity:isInMissionRoom() then
        return false
    end
    --- 进入状态
    entity:enterStateType(Define.RoleStatus.IN_TELEPORT)
    entity:sendPacket({
        pid = "C2STeleportWait",
    })
    local args = {
        fadeInCb = function()
            local packet = {
                pid = "C2STeleportMap",
                map = mapName,
                setBorn = setBorn and 1 or 0
            }
            if position then
                packet.pos = { x = position.x, y = position.y, z = position.z }
            end
            entity:sendPacket(packet, function(stateCode)
                entity:exitStateType(Define.RoleStatus.IN_TELEPORT)
                if finish then
                    finish(stateCode == 0)
                end
            end)
        end,
        fadeOutEvent = "EVENT_SCENE_OBJECT_TELEPORT_MAP",
    }
    UI:openWindow("UI/game_role_common/gui/win_fade_mask", nil, nil, args)
    return true
end

--- 传送至指定地图传送门位置
---@param mapName any
---@param toTeleportId any
---@param finish function 传送完毕回调，传入参数是否成功
---@return boolean 是否成功触发传送
function Entity:teleportToMapTeleportGate(mapName, toTeleportId, finish)
    ---@type Entity
    local entity = self
    if entity:isInStateType(Define.RoleStatus.IN_TELEPORT) then
        return false
    end
    --- 进入状态
    entity:enterStateType(Define.RoleStatus.IN_TELEPORT)
    entity:sendPacket({
        pid = "C2STeleportWait",
    })
    local args = {
        fadeInCb = function()
            entity:sendPacket({
                pid = "C2STeleportMap",
                map = mapName,
                tid = toTeleportId,
            }, function(stateCode)
                entity:exitStateType(Define.RoleStatus.IN_TELEPORT)
                if finish then
                    finish(stateCode == 0)
                end
            end)
        end,
        fadeOutEvent = "EVENT_SCENE_OBJECT_TELEPORT_MAP",
    }
    UI:openWindow("UI/game_role_common/gui/win_fade_mask", nil, nil, args)
    return true
end
