---
--- Generated by PluginCreator
--- player_action player
--- DateTime:2023-05-09
---

local Player = Player
function Player:playPlayerAction(action)
    if self:canPlayPlayerAction()  then
        self:sendPacket({pid="C2SPlayPlayerAction",action=action})
    else
        --print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! cannot playPlayerAction")
    end
end
