---
--- Generated by PluginCreator
--- game_coin entity_func
--- DateTime:2023-02-03
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
--function Entity.ValueFunc:xxx(value)
--    Lib.emitEvent(Event.xxx,1,value)
--end
