---
--- Generated by PluginCreator
--- game_role_common player
--- DateTime:2023-03-03
---

local Player = Player
---@type SkillConfig
local SkillConfig = T(Config, "SkillConfig")

function Player:requestCostMp(skills,callBack)
    if type(skills) == 'table' then
        local mp = 0
        for _, skillId in pairs(skills) do
            local config = SkillConfig:getSkillConfig(skillId or 0)
            if config and config.mpCost then
                mp = mp + config.mpCost
            end
        end
        if mp <= 0 then
            return
        end
    else
        local config = SkillConfig:getSkillConfig(skills or 0)
        if config and config.mpCost then
            local mp = config.mpCost
            if mp <= 0 then
                return
            end
        end
    end

    self:sendPacket({
        pid = "C2SClientChangeMp",
        skills = skills,
    },function (value)
        if callBack then
            callBack(value)
        end
    end)
end
