---
--- Generated by PluginCreator
--- new_game_report entity_common
--- DateTime:2023-04-20
---

local ValueDef = T(Entity, "ValueDef")
-- key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
--ValueDef.xxx 					= {false,   false,  true,   false,      0,                      true}
local Entity = Entity

ValueDef.switchPointSetTime = {false,   false,  false,   false,      0,                      true}   --- 上一次切换方案时间
ValueDef.tAbilityGainTime   = {false,   false,  false,   false,      {},                      true}   --- 能力获取时间，uid作为key
ValueDef.tAbilityGainCount  = {false,   false,  false,   false,      {},                      true}   --- 能力获取次数，alias作为key
ValueDef.levelUpTime        = {false,   false,  false,   false,      0,                      true}   --- 升级时间戳
ValueDef.firstHitMonster  = {false,   false,  false,   false,      0,                      true}   --- 第一次打击怪物标记
ValueDef.firstHitEntity  = {false,   false,  false,   false,      0,                      true}   --- 第一次打击实体标记
ValueDef.firstBeHitEntity  = {false,   false,  false,   false,      0,                      true}   --- 第一次被实体攻击标记

function Entity:setFirstHitMonster(value)
    self:setValue("firstHitMonster", value)
end

function Entity:isFirstHitMonster()
    return (self:getValue("firstHitMonster") or 0) == 1
end

function Entity:setFirstHitEntity(value)
    self:setValue("firstHitEntity", value)
end

function Entity:isFirstHitEntity()
    return (self:getValue("firstHitEntity") or 0) == 1
end

function Entity:setFirstBeHitEntity(value)
    self:setValue("firstBeHitEntity", value)
end

function Entity:isFirstBeHitEntity()
    return (self:getValue("firstBeHitEntity") or 0) == 1
end

function Entity:setSwitchPointSetTime(value)
    self:setValue("switchPointSetTime", value)
end

function Entity:getSwitchPointSetTime()
    return self:getValue("switchPointSetTime")
end

--- 添加能力获取时间
---@param id any
---@param time any
function Entity:addAbilityGainTime(id)
    local tAbilityGainTime = self:getValue("tAbilityGainTime") or {}
    tAbilityGainTime[id] = os.time()
    self:setValue("tAbilityGainTime", tAbilityGainTime)
end

--- 移除能力获取时间
---@param id any
function Entity:removeAbilityGainTime(id)
    local tAbilityGainTime = self:getValue("tAbilityGainTime")
    if tAbilityGainTime and tAbilityGainTime[id] then
        tAbilityGainTime[id] = nil
        self:setValue("tAbilityGainTime", tAbilityGainTime)
    end
end

--- 能力获取时间
---@param id any
function Entity:getAbilityGainTime(id)
    local tAbilityGainTime = self:getValue("tAbilityGainTime")
    if tAbilityGainTime then
        return tAbilityGainTime[id] or 0
    end
    return 0
end

--- 添加能力获取次数
---@param id any
---@param count any
function Entity:addAbilityGainCount(alias, count)
    local tAbilityGainCount = self:getValue("tAbilityGainCount") or {}
    tAbilityGainCount[alias] = (tAbilityGainCount[alias] or 0) + (count or 1)
    self:setValue("tAbilityGainCount", tAbilityGainCount)
end

--- 能力获取次数
---@param id any
function Entity:getAbilityGainCount(alias)
    local tAbilityGainCount = self:getValue("tAbilityGainCount")
    if tAbilityGainCount then
        return tAbilityGainCount[alias] or 1
    end
    return 1
end

function Entity:setLevelUpTime(value)
    self:setValue("levelUpTime", value)
end

function Entity:getLevelUpTime()
    return self:getValue("levelUpTime")
end