---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/8/10 9:51
---

local handles = T(Player, "PackageHandlers")
local RankCommand = T(Lib, "RankCommand")
--缓存
function handles:requestAllRank(packet)
    RankCommand.getRankData(self.platformUserId, packet.rankType,packet.pageNo)
end
--实时
function handles:requestAllRankRealTime(packet)
    if packet.rankId==Define.RANK_ROOM_ID then
        local rankList=RankCommand:getRoomRankList()
        self:sendPacket({
            pid = "allRank",
            rankType = packet.rankType,
            rankList = rankList,
        })
    else
        RankCommand.getRankData(self.platformUserId, packet.rankType,packet.pageNo,true)
    end
end
--缓存
function handles:requestSingleAllRank(packet)
    if packet.rankId==Define.RANK_ROOM_ID then
        local rankData=RankCommand:getRoomSingleRank(self)
        if rankData then
            --print("======================handles:requestSingleAllRank",Lib.v2s(rankData))
            self:sendPacket({
                pid = "singleRank",
                userId = self.platformUserId,
                rankType = packet.rankType,
                score = rankData.score,
                rank = rankData.rank,
                level=rankData.level or 1
            })
        end
    else
        RankCommand.getSingleRank(packet.userId, packet.rankType)
    end
end
--实时
--function handles:requestSingleAllRankRealTime(packet)
--    RankCommand.getSingleRank(packet.userId, packet.rankType,true)
--end

function handles:requestPlayerSkin(packet)
    if not packet or not packet.userId then
        return nil
    end
    --print("--------------------requestPlayerSkin ",packet.userId)
    local url = string.format("%s/decoration/api/v1/inner/decorations/user-decoration", AsyncProcess.ServerHttpHost)
    local args = {
        {"userId", packet.userId},
        {"engineVersion", EngineVersionSetting:getEngineVersion()},
    }

    AsyncProcess.HttpRequest("GET", url, args, function (response)
        --print("-----------------requestPlayerSkin response",response.code)
        if response.code == 1 then
            --print("--------------------requestPlayerSkin success",packet.userId,Lib.v2s(response.data,5))
            self:sendPacket({pid="S2CPlayerSkinData",skinData=response.data.decorationMap,userId=packet.userId,index=packet.index,sex=response.data.sex})
        end
    end)
end

function handles:requestRankTop3()
    local top3List=RankCommand:getRoomRankListTop3()
    if top3List and next(top3List)~=nil then
        RankCommand:syncTop3Data(top3List)
    end
end