---
--- Generated by PluginCreator
--- new_limited_time_activity handler
--- DateTime:2023-04-17
---

local handles = T(Player, "PackageHandlers")
--function handles:Xxxxx(packet)
--end
---@type LimitTimeClientHelper
local LimitTimeClientHelper = T(Lib, "LimitTimeClientHelper")

function handles:SyncPlayLimitedTimeGoldWheelResult(packet)
    --print("----packet---- SyncPlayLimitedTimeGoldWheelResult",Lib.v2s(packet))
    local addition = packet.addition
    if addition and addition.isSucceed then
        Lib.emitEvent(Event.EVENT_GET_LIMITED_TIME_GOLD_WHEEL_RESULT, addition)
    end
    self.inPlayLimitedTimeGoldWheel = false
end

function handles:SyncCombinationLimitTimeResult(packet)
    local addition = packet.addition
    if addition and addition.isSucceed then
        Me:showAwardPopup(addition)
    end
    Lib.emitEvent(Event.EVENT_LIMITED_TIME_BUY_RESULT, false)
end

function handles:SyncLimitedTimeGoldWheelActivity(packet)
    LimitTimeClientHelper:updateActiveData( Define.LIMITED_TIME_ACTIVITY_TYPE.LIMITED_TIME_GOLD_WHEEL, packet.status, packet.params)
    Lib.emitEvent(Event.EVENT_UPDATE_LIMITED_TIME_ACTIVITY)
    LimitedTimeActivityGameMgr:updateLimitedTimeActivityBtnShow()
    LimitedTimeActivityGameMgr:updateGoldenWheelBtnShow()
    LimitTimeClientHelper:checkLimitedTimeActivityRedDot(Define.LIMITED_TIME_ACTIVITY_TYPE.LIMITED_TIME_GOLD_WHEEL)
end
