---
--- Generated by PluginCreator
--- new_limited_time_activity player
--- DateTime:2023-04-17
---

local Player = Player
--function Player:xxxxx()
--end


function Player:showAwardPopup(addition, title)
    UI:openWindow("UI/new_limited_time_activity/gui/win_award_popup", nil, nil, addition, title)
end

function Player:showCombinedLimitTimeCardRewards()
    if not self.inShowLimitedTimeActivityAwardPopup and self.combinedLimitTimeCardRewards and self.combinedLimitTimeCardRewards[1] then
        local cardType = self.combinedLimitTimeCardRewards[1].item.cardType
        self:showAwardPopup(self.combinedLimitTimeCardRewards[1], "gui.limit.time.card.congratulations"..cardType)
        table.remove(self.combinedLimitTimeCardRewards, 1)
    end
end