---
--- Generated by PluginCreator
--- task_system entity
--- DateTime:2023-03-23
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
