---
--- Generated by PluginCreator
--- npc_system handler
--- DateTime:2023-03-29
---

local handles = T(Player, "PackageHandlers")
---@type ItemConfig
local ItemConfig = T(Config, "ItemConfig")

--- npc抽奖回调
---@param packet any
function handles:SCNpcLuckyDrawResult(packet)
    local stateCode = packet.stateCode
    if stateCode == 0 then
        if packet.item_alias and packet.item_alias ~= "" then
            local itemCfg = ItemConfig:getCfgByItemAlias(packet.item_alias)
            local name = itemCfg.name
            if Define.ITEM_QUALITY_FONT_COLOR[itemCfg.quality_alias] then
                local color = string.format("[colour='%s']", Define.ITEM_QUALITY_FONT_COLOR[itemCfg.quality_alias])
                name = color .. Lang:toText(name)
            end
            local text = Lang:toText({ "g2069_gain_reward_tips", name })
            if packet.item_num > 1 then
                local color2 = string.format("[colour='%s']", World.cfg.fly_new_tipsSetting.textColours)
                text = text .. color2 .. "+" .. packet.item_num
            end
            Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", text)
        else
            Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", "g2069_shop_buy_success")
        end
    elseif stateCode == 2 then
        local name = ItemConfig:getName(packet.item_alias)
        local text = Lang:toText({ "g2069_not_enough_coin", name })
        Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", text)
    else
        Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", "g2069_shop_buy_fail")
    end
end
