---
--- Generated by PluginCreator
--- npc_system player
--- DateTime:2023-03-29
---

local Player = Player
---@type WalletSystem
local WalletSystem = T(Lib, "WalletSystem")
---@type ItemConfig
local ItemConfig = T(Config, "ItemConfig")
---@type NpcRewardSettingConfig
local NpcRewardSettingConfig = T(Config, "NpcRewardSettingConfig")
---@type GrowthSystem
local GrowthSystem = T(Lib, "GrowthSystem")

function Player:doNPCLuckyDrawBuyPool(groupId)
    if not groupId then
        return
    end
    local dialogDrawTime = Me:getDialogDrawTime()
    local curLevel = GrowthSystem:getLevel(Me)
    local rewardCfg
    if dialogDrawTime[groupId] then
        rewardCfg = NpcRewardSettingConfig:getCfgByGroupAndLv(groupId, curLevel)
    else -- 首次抽奖
        local firstDraw = NpcRewardSettingConfig:getCfgByGroupAFirst(groupId, curLevel)
        if firstDraw then
            rewardCfg = firstDraw
        else
            rewardCfg = NpcRewardSettingConfig:getCfgByGroupAndLv(groupId, curLevel)
        end
    end

    if rewardCfg then
        local coinNum = rewardCfg.kValue*curLevel + rewardCfg.bValue
        local isUseScribe = false
        if self:isCanUseFreeLuckyDraw() then
            coinNum = 0
            isUseScribe = true
        end
        local coinName = rewardCfg.item_alias
        local myCoin = WalletSystem:getCoin(Me, coinName)
        if myCoin < coinNum then
            local name = ItemConfig:getName(coinName)
            Me:showGameTopTips(Lang:toText({ "g2069_not_enough_coin", name }))
            if coinName == Define.ITEM_ALIAS.GOLDEN_CUBE then
                Interface.onRecharge(1)
            end
            return
        end

        Me:sendPacket({
            pid = "C2SBuyNpcLuckyDraw",
            groupId = groupId,
            isUseScribe = isUseScribe
        })
    end
end
