---
--- Generated by PluginCreator
--- jump_control entity
--- DateTime:2023-03-03
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
