---
--- Generated by PluginCreator
--- timelight entity_func
--- DateTime:2021-11-04
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
--function Entity.ValueFunc:xxx(value)
--    Lib.emitEvent(Event.xxx,1,value)
--end
