---
--- Generated by PluginCreator
--- game_common define
--- DateTime:2023-02-24
---

-- color 对应setting atlas
Define.FlyTextType = {
    Damage = {
        color = 1,
        scale = 1
    }, --受到普通伤害
    BlastDamage = {
        color = 3,
        scale = 1
    }, --受到暴击伤害
    PlayerSelfDamage = {
        color = 2,
        scale = 1
    }, --玩家自己受到伤害
    PlayerOtherDamage = {
        color = 4,
        scale = 1
    }, --其他玩家受到普通伤害
    MissDamage = {
        color = 5,
        scale = 1
    }, --闪避
    WhiteDamage = {
        color = 6,
        scale = 1
    }, --UI图集白字
    MissSelfDamage = {
        color = 7,
        scale = 1
    },--玩家自己的闪避
    ShootDownFlyPlayer = {
        color = 8,
        scale = 1
    },--击落飞行玩家
}

Define.VarKey = {
    Skills = "skills", ---技能信息
    EquippedSkills = "equippedSkills", ---已装备的技能
    SkillCDRecord = "skillCDRecord", ---技能CD记录
}

Define.CollisionGroup = {
    Base = 1,           -- 默认场景物件   group1
    Player = 2,         -- 玩家   group2
    Monster = 4,        -- 怪物   group3
    SceneProp= 8,       --场景道具 group4
    Missile= 16,        --子弹 group5
    Missile2= 32,        --子弹2(不碰撞零件) group6
}

Define.TargetConditionKey = {
    LEVEL = "LEVEL",                -- 人物等级
    NPC = "NPC",                    -- NPC对话情况
    LOCATION = "LOCATION",          -- 进入区域
    ITEM= "ITEM",                   -- 拥有物品
    KILL= "KILL",                   -- 击杀怪物
    ABILITY= "ABILITY",             -- 能力等级
    TASK= "TASK",                   -- 任务完成情况
    BORN = "BORN",                -- 出生开启
    MISSION = "MISSION",                -- 通关副本
}

Define.PKModeType = {
    safe = 0,                -- 安全模式
    pkWait = 1,                    -- 等待进入PK状态
    pk1 = 2,                    -- pk模式1
    pk2 = 3,                -- pk模式2
}

Define.PKReportKey = {
    [Define.PKModeType.safe] = "safe",                -- 安全模式
    [Define.PKModeType.pkWait] = "safe",                    -- 等待进入PK状态
    [Define.PKModeType.pk1] = "pk1",                    -- pk模式1
    [Define.PKModeType.pk2] = "pk2",                -- pk模式2
}