---
--- Generated by PluginCreator
--- game_mission entity
--- DateTime:2023-06-14
---

local Entity = Entity

---@type MissionStageWaveInfoConfig
local MissionStageWaveInfoConfig = T(Config, "MissionStageWaveInfoConfig")

--- 进入任务
---@param missionRoomId string
---@param finish function 
function Entity:enterMission(missionRoomId, finish)
    ---@type Entity
    local entity = self
    if entity:isInStateType(Define.RoleStatus.IN_TELEPORT) then
        return false
    end
    --- 进入状态
    entity:enterStateType(Define.RoleStatus.IN_TELEPORT)
    entity:sendPacket({
        pid = "C2SEnterMissionWait",
    })
    local args = {
        fadeInCb = function()
            if not entity or not entity:isValid() then
                return
            end
            entity:sendPacket({
                pid = "C2SEnterMission",
                roomId = missionRoomId,
            }, function(stateCode)
                entity:exitStateType(Define.RoleStatus.IN_TELEPORT)
                if finish then
                    finish(stateCode == 0)
                end
            end)
        end,
        fadeOutEvent = "EVENT_GAME_MISSION_ENTER_MISSION",
    }
    UI:openWindow("UI/game_role_common/gui/win_fade_mask", nil, nil, args)

    return true
end

--- 触发怪物对话
function Entity:checkTriggerMissionDialog()
    if not self._missionDialogs then
        local data = self:getMissionMonsterData()
        if data and data.wid then
            --- 初始化数据
            local config = MissionStageWaveInfoConfig:getCfgById(data.wid)
            local hp_losts = config.hp_losts
            local hp_tips = config.hp_tips
            self._missionDialogs = {}
            if hp_losts then
                for index, percent in pairs(hp_losts) do
                    self._missionDialogs[#self._missionDialogs + 1] = { percent = percent, dialog = hp_tips[index], trigger = false }
                end
            end
        end
    end
    if self._missionDialogs and #self._missionDialogs > 0 then
        local curHp = self.curHp
        local maxHp = self:prop("maxHp")
        local p = 1
        if maxHp ~= 0 then
            p = curHp / maxHp
        end
        for _, data in pairs(self._missionDialogs) do
            if p > data.percent then
                break
            end
            if not data.trigger then
                data.trigger = true
                --- 触发对话
                Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", data.dialog)
            end
        end
    end
end