---
--- Generated by PluginCreator
--- jump_control mainLua
--- DateTime:2023-03-03
---

require "common.entity_jump_control"
require "common.event_jump_control"
require "common.define_jump_control"

if World.isClient then
    require "client.player.player_jump_control"
    require "client.player.packet_jump_control"
    require "client.entity.entity_jump_control"
    require "client.entity.entity_value_func_jump_control"
    require "client.gm_jump_control"
else
    require "server.player.player_jump_control"
    require "server.player.packet_jump_control"
    require "server.entity.entity_jump_control"
    require "server.gm_jump_control"
end

local handlers = {}

--function handlers.openXXXWnd()
	--TODO
--end

return function(name, ...)
	if type(handlers[name]) ~= "function" then
		return
	end
	return handlers[name](...)
end
