---
--- Generated by PluginCreator
--- game_coin gm
--- DateTime:2023-02-03
---
local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

GMItem["游戏货币/货币兑换"] = function()
    UI:openWindow("UI/game_coin/window/win_coin_exchange")
end
