---
--- Generated by PluginCreator
--- g2060_friend player
--- DateTime:2022-07-07
---

local Player = Player

function Player:isFollowCdFinish()
    return (os.time() - self:getLastFollowTime()) > World.cfg.g2060_friendSetting.followCd
end
