---
--- Generated by PluginCreator
--- fly_new_tips entity
--- DateTime:2023-04-17
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
