---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/11/16 15:14
---
---@class LimitedTimeActivityGameMgr
local LimitedTimeActivityGameMgr = LimitedTimeActivityGameMgr
---@type LimitedTimeActivityConfig
local LimitedTimeActivityConfig = T(Config, "LimitedTimeActivityConfig")
---@type LimitTimeClientHelper
local LimitTimeClientHelper = T(Lib, "LimitTimeClientHelper")
---@type LimitedTimeGiftCombinedConfig
local LimitedTimeGiftCombinedConfig = T(Config, "LimitedTimeGiftCombinedConfig")
---@type LimitedTimeGiftSignalConfig
local LimitedTimeGiftSignalConfig = T(Config, "LimitedTimeGiftSignalConfig")
---@type LimitedTimeGiftItemConfig
local LimitedTimeGiftItemConfig = T(Config, "LimitedTimeGiftItemConfig")


---@type ItemConfig
local ItemConfig = T(Config, "ItemConfig")

if World.isClient then
    function LimitedTimeActivityGameMgr:updateCombinedLimitBtnShow(isOpen)
        Lib.emitEvent(Event.EVENT_NEW_LIMITED_TIME_ACTIVITY_UPDATE_COMBINATION_GIFT, isOpen)
    end

    function LimitedTimeActivityGameMgr:updateGoldenWheelBtnShow()
        local isOpen = LimitTimeClientHelper:checkActiveIsOpen(Define.LIMITED_TIME_ACTIVITY_TYPE.LIMITED_TIME_GOLD_WHEEL)
        Lib.emitEvent(Event.EVENT_NEW_LIMITED_TIME_ACTIVITY_UPDATE_GOLDEN_WHEEL, isOpen)
    end

    function LimitedTimeActivityGameMgr:showBuyFailTip()
        Me:showGameTopTips(Lang:toText("g2069_not_enough_golden_cube"))
        Interface.onRecharge(1)
    end

    function LimitedTimeActivityGameMgr:clientClickBoughtBtn(activityType, params)
        if activityType == Define.LIMITED_TIME_ACTIVITY_TYPE.COMBINATION_GIFT then
            Lib.emitEvent(Event.EVENT_LIMITED_TIME_BUY_RESULT, true)
            Me:sendPacket({
                pid = "CSBuyLimitCombinationGift",
                activityId = params.activityId,
                id = params.id,
            })
        end
    end

    function LimitedTimeActivityGameMgr:showBoughtResultTips(info)
        if info.result then
            local giftNum = info.giftNum or 1
            if giftNum <= 0 then
                giftNum = 1
            end
            local item
            if info.activityType == Define.LIMITED_TIME_ACTIVITY_TYPE.COMBINATION_GIFT then
                item = LimitedTimeGiftCombinedConfig:getCfgById(info.id)
            end
            if item then
                local addition = {
                    isSucceed = true,
                    item = item
                }
                addition.showItemBg = #item.giftContent > 1
                Me:showAwardPopup(addition)
            else
                Me:showGameTopTips(Lang:toText("gui.limit.time.buy.success"))
            end
        else
            Me:showGameTopTips(Lang:toText("gui.limit.time.buy.fail"))
        end
    end

    function LimitedTimeActivityGameMgr:limitTimeAwardItemClickFunc(data, dx, dy)
        local item = self:getItemInfo(data)
        UI:openWindow("UI/new_limited_time_activity/gui/win_item_info", nil, nil, item)
    end

    function LimitedTimeActivityGameMgr:getItemInfo(item)
        local data = {}
        local itemId = item.itemId
        local config = ItemConfig:getCfgByItemId(itemId)
        data.itemIcon = config.icon
        data.itemCount = item.itemCount
        data.itemName = config.name
        data.quality = config.quality_alias
        data.itemType = config.type_alias
        data.itemDesc = config.desc
        data.itemId = itemId
        return data
    end
else
    --- 购买成功
    ---@param player any
    ---@param item any
    function LimitedTimeActivityGameMgr:onBuySuccess(player, item)
        Plugins.CallTargetPluginFunc("game_role_common", "addLimitedActivityRewards", player, item)
    end
end