---
--- Generated by PluginCreator
--- g2060_friend handler
--- DateTime:2022-07-07
---

local handles = T(Player, "PackageHandlers")
local FriendSpecialData = T(Lib, "FriendSpecialData")

function handles:S2CPlayerSpecialData(packet)
    FriendSpecialData:setClientSpecialData(packet.specialDataList)
    Lib.emitEvent(Event.EVENT_G2060_FRIEND_GET_SPECIAL_DATA, packet.specialDataList)
end


function handles:S2CShowFollowTips(packet)
    UserInfoCache.LoadCacheByUserIds({packet.targetUserId}, function ()
        local data = UserInfoCache.GetCache(packet.targetUserId) or {}
        self:showGameTopTips(Lang:toText({"g2060_friend_follow_ing", data.nickName}))
    end)
end