---
--- Generated by PluginCreator
--- g2060_friend player
--- DateTime:2022-07-07
---

local Player = Player

function Player:sendPlayerFollow(targetUserId, content, crossServer)
    self:sendPacket({
        pid = "C2SPlayerFollow",
        targetUserId = targetUserId,
        content = content,
        crossServer = crossServer,
    })
end