---
--- Generated by PluginCreator
--- game_mission gm
--- DateTime:2023-06-14
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

---@type GameRoleCommonGMHelperServer
local GameRoleCommonGMHelperServer = T(Lib, "GameRoleCommonGMHelperServer")

GMItem["副本/创建怪物"] = function(self)
    if not World.cfg.openGM then
        return
    end
    if self.testMissionMonster and self.testMissionMonster:isValid() then
        Plugins.CallTargetPluginFunc("monster_manager", "doDestroyMonster", self.testMissionMonster.objID)
    end

    local map = self.map
    local monsterId = 1003
    local myPos = self:getPosition()
    local pos = Lib.v3(myPos.x + 1, myPos.y, myPos.z + 1)
    self.testMissionMonster = Plugins.CallTargetPluginFunc("monster_manager", "doCreateMonster", map, monsterId, pos)
end

GMItem["副本/销毁怪物"] = function(self)
    if not World.cfg.openGM then
        return
    end
    if self.testMissionMonster and self.testMissionMonster:isValid() then
        Plugins.CallTargetPluginFunc("monster_manager", "doDestroyMonster", self.testMissionMonster.objID)
    end
    self.testMissionMonster = nil
end

GMItem["副本/打印次数"] = function(self)
    if not World.cfg.openGM then
        return
    end
    local missionCountInfo = self:getMissionCountInfo()
    print("副本次数", Lib.v2s(missionCountInfo))
end
