---
--- Generated by PluginCreator
--- game_time handler
--- DateTime:2021-11-26
---
---@type GameTimes
local GameTimes = T(Lib, "GameTimes")
local handles = T(Player, "PackageHandlers")
function handles:adjustGameTime(packet)
    GameTimes:adjustGameTime(packet)
end
