---
--- Generated by PluginCreator
--- new_chat handler
--- DateTime:2022-01-06
---
local ChatPage = Define.ChatPage
local handles = T(Player, "PackageHandlers")

function handles:SendChatMsgToClient(packet)
    local msgData = packet.msgData
    Lib.emitEvent(Event.EVENT_RECEIVE_CHAT_MESSAGE, msgData)
    self:showChatBubble(msgData)
end

function handles:BuyVoiceResult(packet)
    if not packet.isSucceed then
        Interface.onRecharge(1)
    end
    Client.ShowTip(1, Lang:toText(packet.isSucceed and "new.chat.voiceBuySucc" or "new.chat.voiceBuyFail"), 40)
end