---
--- Generated by PluginCreator
--- engine_overwrite gm
--- DateTime:2023-02-24
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
--GMItem["engine_overwrite/一个彩蛋"] = function()
--end
