---
--- Generated by PluginCreator
--- game_coin mainLua
--- DateTime:2023-02-03
---
require "common.entity_game_coin"
require "common.event_game_coin"
require "common.define_game_coin"
require "common.system.wallet_system"

if World.isClient then
    require "client.player.player_game_coin"
    require "client.player.packet_game_coin"
    require "client.entity.entity_game_coin"
    require "client.entity.entity_value_func_game_coin"
    require "client.gm_game_coin"
else
    require "server.player.player_game_coin"
    require "server.player.packet_game_coin"
    require "server.entity.entity_game_coin"
    require "server.gm_game_coin"
end

local handlers = {}

-- function handlers.openXXXWnd()
-- TODO
-- end

return function(name, ...)
    if type(handlers[name]) ~= "function" then
        return
    end
    return handlers[name](...)
end
