---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/6/28 20:20
---
Event.EVENT_CONNECTOR_MSG = Event.register("EVENT_CONNECTOR_MSG")
Event.EVENT_SERVER_CONNECTOR_MSG = Event.register("EVENT_SERVER_CONNECTOR_MSG")