---
--- Generated by PluginCreator
--- connector gm
--- DateTime:2021-10-20
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
--GMItem["connector/一个彩蛋"] = function()
--end
