---
--- Generated by PluginCreator
--- player_action mainLua
--- DateTime:2023-05-09
---

require "common.config.player_action_config"
require "common.entity_player_action"
require "common.event_player_action"
require "common.define_player_action"
if World.isClient then
    require "client.player.player_player_action"
    require "client.player.packet_player_action"
    require "client.entity.entity_player_action"
    require "client.entity.entity_value_func_player_action"
    require "client.gm_player_action"
else
    require "server.player.player_player_action"
    require "server.player.packet_player_action"
    require "server.entity.entity_player_action"
    require "server.gm_player_action"
end

local handlers = {}

--function handlers.openXXXWnd()
	--TODO
--end



return function(name, ...)
	if type(handlers[name]) ~= "function" then
		return
	end
	return handlers[name](...)
end
