---
--- Generated by PluginCreator
--- task_system mainLua
--- DateTime:2023-03-23
---

require "common.entity_task_system"
require "common.event_task_system"
require "common.config.task_config"
require "common.define_task_system"
if World.isClient then
    require "client.player.player_task_system"
    require "client.player.packet_task_system"
    require "client.entity.entity_task_system"
    require "client.entity.entity_value_func_task_system"
    require "client.gm_task_system"
else
    require "server.task_system_helper"
    require "server.player.player_task_system"
    require "server.player.packet_task_system"
    require "server.entity.entity_task_system"
    require "server.gm_task_system"
end

local handlers = {}

if World.isClient then

else
    ---@type TaskConfig
    local TaskConfig = T(Config, "TaskConfig")

    -- 服务端登陆,重新检测可接任务
    function handlers.OnPlayerLogin(player)
        local allTask = TaskConfig:getAllCfgs()
        for taskId, taskConfig in pairs(allTask) do
            if taskConfig.taskType == Define.TaskType.Main and taskConfig.autoIssue then
                player:receiveOneTask(taskId)
            elseif taskConfig.taskType == Define.TaskType.Branch and taskConfig.autoIssue and taskConfig.branchLogin then
                player:receiveOneTask(taskId)
            end
        end
    end
end

return function(name, ...)
	if type(handlers[name]) ~= "function" then
		return
	end
	return handlers[name](...)
end
