---
--- Generated by PluginCreator
--- camera_edit entity_common
--- DateTime:2023-05-25
---

local ValueDef = T(Entity, "ValueDef")
 --key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
ValueDef.firstInMapList 		= {false,   true,  true,   false,      {},                      true}
local Entity = Entity

function Entity:isFirstWelcome(mapName)
    print("Entity:isFirstWelcome:",mapName)
    if not mapName  then
        return
    end
    local data = self:getValue("firstInMapList")
    if data[mapName] then
        return
    end
    data[mapName] = true
    self:setValue("firstInMapList",data)
    Me:showWelcome(mapName)
end