---
--- Generated by PluginCreator
--- task_system gm
--- DateTime:2023-03-23
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end

GMItem["任务/领取任务"] = GM:inputStr(function(self, value)
    if not World.cfg.openGM then
        return
    end
    self:receiveOneTask(tonumber(value), true)
end)

GMItem["任务/放弃任务"] = GM:inputStr(function(self, value)
    if not World.cfg.openGM then
        return
    end
    self:giveUpOneTask(tonumber(value), true)
end)

GMItem["任务/完成任务"] = GM:inputStr(function(self, value)
    if not World.cfg.openGM then
        return
    end
    self:completeOneTask(tonumber(value))
end)

GMItem["任务/清空任务"] = function(self)
    if not World.cfg.openGM then
        return
    end
    self:cleanTaskData()
end


