---
--- Generated by PluginCreator
--- game_time define
--- DateTime:2021-11-26
---

Define.GameTimeDay = {
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
}
