---
--- Generated by PluginCreator
--- player_action entity
--- DateTime:2023-05-09
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
