---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bell.
--- DateTime: 2020/3/25 22:21
---

if World.isClient then
    Event.EventCastSkill = Event.register("EventCastSkill")
    Event.EventButtonCDTimer = Event.register("EventButtonCDTimer")
    Event.EVENT_SWITCH_SKILL_UPDATE = Event.register("EVENT_SWITCH_SKILL_UPDATE")
    Event.EVENT_RESET_SKILL = Event.register("EVENT_RESET_SKILL")
    Event.EVENT_RESUME_SKILL = Event.register("EVENT_RESUME_SKILL")
    Event.EVENT_SPRINT_NUM_CHANGE = Event.register("EVENT_SPRINT_NUM_CHANGE")
    Event.EVENT_SPRINT_NUM_RECOVER = Event.register("EVENT_SPRINT_NUM_RECOVER")
else
    Event.EventGameSkillResult = Event.register("EventGameSkillResult")
end