---
--- Generated by PluginCreator
--- game_book mainLua
--- DateTime:2023-06-19
---

require "common.entity_game_book"
require "common.event_game_book"
require "common.config.book_info_config"
require "common.config.book_reward_config"
require "common.define_game_book"
if World.isClient then
    require "client.player.player_game_book"
    require "client.player.packet_game_book"
    require "client.entity.entity_game_book"
    require "client.entity.entity_value_func_game_book"
    require "client.gm_game_book"
else
    require "server.player.player_game_book"
    require "server.player.packet_game_book"
    require "server.entity.entity_game_book"
    require "server.gm_game_book"
end

local handlers = {}

--function handlers.openXXXWnd()
	--TODO
--end

return function(name, ...)
	if type(handlers[name]) ~= "function" then
		return
	end
	return handlers[name](...)
end
