---
--- Generated by PluginCreator
--- engine_overwrite entity_common
--- DateTime:2023-02-24
---

local ValueDef = T(Entity, "ValueDef")
-- key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
--ValueDef.xxx 					= {false,   false,  true,   false,      0,                      true}
local Entity = Entity
