---
--- Generated by PluginCreator
--- camera_edit entity_func
--- DateTime:2023-05-25
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
--function Entity.ValueFunc:curMap(value)
--    print("DSFGDFADAFSFGDSGDFDASFGSDFG")
--    if value and value ~= "map_born" then
--        self:isFirstWelcome(value)
--    end
--
--end
Lib.subscribeEvent(Event.EVENT_CLIENT_CHANGE_SCENE_MAP, function(mapName)
    print("DSFGDFADAFSFGDSGDFDASFGSDFG")
    Me:isFirstWelcome(mapName)
end)
