---
--- Generated by PluginCreator
--- game_business define
--- DateTime:2023-04-10
---

--Define.XXX_XX_X = 0.2 

--- 商店标签
Define.SHOP_TAB = {
    PROPS = "props",
    PRIVILEGE = "privilege",
    RESOURCES = "resources",
}

--- 商店标签名称
Define.SHOP_TAB_NAME = {
    [Define.SHOP_TAB.PROPS] = "g2069_shop_tab_props",
    [Define.SHOP_TAB.PRIVILEGE] = "g2069_shop_tab_privilege",
    [Define.SHOP_TAB.RESOURCES] = "g2069_shop_tab_resources",
}
