---
--- Generated by PluginCreator
--- game_business event
--- DateTime:2023-04-10
---

Event.EVENT_GAME_BUSINESS_SHOP_BUY = Event.register("EVENT_GAME_BUSINESS_SHOP_BUY")

if World.isClient then
--    Event.EVENT_GAME_BUSINESS_XXX = Event.register("XXX_XXX_XX")
    Event.EVENT_GAME_BUSINESS_UI_SELECT_SHOP_TAB = Event.register("EVENT_GAME_BUSINESS_UI_SELECT_SHOP_TAB")
    Event.EVENT_GAME_BUSINESS_UI_SELECT_SHOP_ITEM = Event.register("EVENT_GAME_BUSINESS_UI_SELECT_SHOP_ITEM")

    
else

end
