---
--- Generated by PluginCreator
--- game_coin event
--- DateTime:2023-02-03
---

Event.EVENT_GAME_COIN_CHANGE_COIN_NUM = Event.register("EVENT_GAME_COIN_CHANGE_COIN_NUM")

if World.isClient then
--    Event.EVENT_GAME_COIN_XXX = Event.register("XXX_XXX_XX")
    Event.EVENT_GAME_COIN_EXCHANGE = Event.register("EVENT_GAME_COIN_EXCHANGE")
else

end
