---
--- Generated by PluginCreator
--- g2060_friend gm
--- DateTime:2022-07-07
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
--GMItem["g2060_friend/获取玩家特殊数据"] = function(self)
--    local FriendSpecialData = T(Lib, "FriendSpecialData")
--    FriendSpecialData:getSpecialData(self.platformUserId, self.platformUserId)
--end