---
--- Generated by PluginCreator
--- game_book player
--- DateTime:2023-06-19
---

local Player = Player
---@type BookRewardConfig
local BookRewardConfig = T(Config, "BookRewardConfig")
---@type InventorySystem
local InventorySystem = T(Lib, "InventorySystem")
---@type BookInfoConfig
local BookInfoConfig = T(Config, "BookInfoConfig")

function Player:isHaveBookRewardRed()
    local haveBookNum = 0
    local allBook = BookInfoConfig:getAllCfgs()
    local inventoryType = Define.ITEM_INVENTORY_TYPE[Define.ITEM_TYPE.ABILITY]
    for _, data in pairs(allBook or {}) do
        local ability = InventorySystem:getItemByItemId(Me, inventoryType, data.abilityId)
        if ability then
            haveBookNum = haveBookNum + 1
        end
    end
    local bookRewardState = self:getBookRewardState()
    local rewardList = BookRewardConfig:getAllCfgs()
    for _, data in pairs(rewardList or {}) do
        if haveBookNum >= data.collectNum then
            if not bookRewardState[data.Id] then
                return true
            end
        end
    end
    return false
end
