---
--- Generated by PluginCreator
--- game_common entity_func
--- DateTime:2023-02-24
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")

function Entity.ValueFunc:safeModeType(value, oldValue)
    self:updateSafeBuffShow()
    if value ~= Define.PKModeType.safe then
        self:setSafeBranchTask(0)
    end
end