---
--- Generated by PluginCreator
--- engine_overwrite player
--- DateTime:2023-02-24
---

local Player = Player

function Player:initPlayer()

    self.jumpRaiseEnd = false
    self.jumpLastMotionY = 0
    self.curJumpClass = nil
    self.jumpRealHeight = 0
    self.startJumpPosy = -99999

    self.lockKeyJump = false

    self.isInAirStatus = 0

    Blockman.Instance():setLockVisionState(World.cfg.lockVision and World.cfg.lockVision.open or false)
end