---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/3/3 17:08
---

local playerEventEngineHandler = L("playerEventEngineHandler", player_event)

local events = {}

local ignoreEngineEvents = {
    resetGameResult = true
}
function player_event(player, event, ...)
    if not ignoreEngineEvents[event] then
        playerEventEngineHandler(player, event, ...)
    end
    local func = events[event]
    if func then
        func(player, ...)
    end
end

function events:fallGround(fallDistance)
    --print("====================fallGround========================", fallDistance)
    self:eventFallGround(fallDistance)
    Lib.emitEvent(Event.EVENT_ENGINE_OVERWRITE_FALL_ON_GROUND,self.objID)
end


function events:leaveGround()
    --print("====================leaveGround========================")
end

function events:dead(dead)
    if dead then
        self:recoverJumpProp()
    end
end