---
--- Generated by PluginCreator
--- game_role_common define
--- DateTime:2023-03-03
---

--Define.XXX_XX_X = 0.2 
--- 角色一级属性
Define.ATTR = {
    MAX_HP = "maxHp",               --- 最大血量
    HP_REGEN = "hpRegen",           --- 血量回复速度
    ATK_DAMAGE = "attDamage",       --- 攻击力
    ELE_DAMAGE = "eleDamage",       --- 元素攻击力
    ATK_DOMINANT = "attDominant",
    ELE_DOMINANT = "eleDominant",
    DEF_DAMAGE = "defDamage",       --- 防御力
    MAX_MP = "maxMp",               --- 最大精力
    MP_REGEN = "mpRegen",           --- 精力回复速度
    MOVE_SPEED = "moveSpeed",       --- 移动速度
    JUMP_SPEED = "jumpSpeed",       --- 跳跃速度
    ATK_CRIT_RATE = "attCrit",      --- 暴击率
    ATK_CRIT_DAMAGE = "attCritDmg", --- 暴击伤害
    DEF_DODGE = "defDodge",         --- 闪避率
    DEF_TOUGH = "defTough",         --- 韧性
    ATK_PRIVILEGE = "attPrivilege", --- 攻击修正
    COIN_RATE = "coinRate",         --- 金币获得率
    EXP_RATE = "expRate",           --- 经验额外获得率
    DAILY_COIN = "dailyCoin",       --- 日常金币获限定值，0为不限
    DAILY_EXP = "dailyExp",         --- 日常经验获限定值，0为不限
    AP_RATE = "apRate",             --- 能力经验获得率
    JUMP_COUNT = "jumpCount",       --- 跳跃次数
    DASH_COUNT = "dashCount",       --- 冲刺次数

    --- 角色二级属性
    HEALTH = "health",              --- 生命
    ATTACK = "attack",              --- 攻击
    DEFENCE = "defence",            --- 防御
    AGILITY = "agility",            --- 敏捷
    ENERGY = "energy",              --- 精力
    ELEMENT_ATTACK = "eleattack",   --- 元素攻击
}

Define.ATTR_MOD_TYPE = {
    RAW = 100,          --- 原生值
    PERCENTADD = 200,   --- 累加
    PERCENTMULT = 300,  --- 累乘
    ADD = 400,          --- 加法
}

Define.ATTR_CLASS = {
    --- 一级属性,都是复合属性
    [Define.ATTR.MAX_HP] = require "common.attribute.max_hp_attribute",
    [Define.ATTR.HP_REGEN] = require "common.attribute.composite_attribute",
    [Define.ATTR.ATK_DAMAGE] = require "common.attribute.composite_attribute",
    [Define.ATTR.ELE_DAMAGE] = require "common.attribute.composite_attribute",
    [Define.ATTR.ATK_DOMINANT] = require "common.attribute.composite_attribute",
    [Define.ATTR.ELE_DOMINANT] = require "common.attribute.composite_attribute",
    [Define.ATTR.DEF_DAMAGE] = require "common.attribute.composite_attribute",
    [Define.ATTR.MAX_MP] = require "common.attribute.max_mp_attribute",
    [Define.ATTR.MP_REGEN] = require "common.attribute.composite_attribute",
    [Define.ATTR.MOVE_SPEED] = require "common.attribute.composite_attribute",
    [Define.ATTR.JUMP_SPEED] = require "common.attribute.composite_attribute",
    [Define.ATTR.ATK_CRIT_RATE] = require "common.attribute.composite_attribute",
    [Define.ATTR.ATK_CRIT_DAMAGE] = require "common.attribute.composite_attribute",
    [Define.ATTR.DEF_DODGE] = require "common.attribute.composite_attribute",
    [Define.ATTR.DEF_TOUGH] = require "common.attribute.composite_attribute",
    [Define.ATTR.ATK_PRIVILEGE] = require "common.attribute.composite_attribute",
    [Define.ATTR.COIN_RATE] = require "common.attribute.composite_attribute",
    [Define.ATTR.EXP_RATE] = require "common.attribute.composite_attribute",
    [Define.ATTR.DAILY_COIN] = require "common.attribute.daily_coin_attribute",
    [Define.ATTR.DAILY_EXP] = require "common.attribute.daily_exp_attribute",
    [Define.ATTR.AP_RATE] = require "common.attribute.composite_attribute",
    [Define.ATTR.JUMP_COUNT] = require "common.attribute.jump_count_attribute",
    [Define.ATTR.DASH_COUNT] = require "common.attribute.dash_count_attribute",

    --- 二级属性,都是可成长属性
    [Define.ATTR.HEALTH] = require "common.attribute.growth_attribute",
    [Define.ATTR.ATTACK] = require "common.attribute.growth_attribute",
    [Define.ATTR.DEFENCE] = require "common.attribute.growth_attribute",
    [Define.ATTR.AGILITY] = require "common.attribute.growth_attribute",
    [Define.ATTR.ENERGY] = require "common.attribute.growth_attribute",
    [Define.ATTR.ELEMENT_ATTACK] = require "common.attribute.growth_attribute",
}

--- buff叠加类型
Define.BUFF_ADD_TYPE = {
    NONE = 0,                            --- 无限制，每个buff独立
    LAYER_STACK_TIME_NO_REFRESH = 1,     --- 堆叠，但时间不刷新
    LAYER_STACK_TIME_REFRESH = 2,        --- 堆叠，且时间刷新
    LAYER_STACK_TIME_EXTEND = 3,         --- 堆叠，且时间延长
    LAYER_NO_STACK_TIME_EXTEND = 4,      --- 不堆叠，且时间延长
    LAYER_NO_STACK_TIME_REFRESH = 5,     --- 不堆叠，且时间刷新
    LAYER_NO_STACK_TIME_NOT_REFRESH = 6, --- 不堆叠，且时间不刷新
}

--- buff行为类
Define.BUFF_ACTION_CLASS = {
    BaseBuffAction = require "common.buff.action.base_buff_action",
    ChangeAttribute = require "common.buff.action.change_attribute",
    EngineBuffAction = require "common.buff.action.engine_buff_action",
}

--- 异常状态
Define.ABNORMAL_STATUS = {
    DIZZINESS = 1,    --- 晕眩
}

--- 物品类型
Define.ITEM_TYPE = {
    ABILITY = "ability",               --- 能力
    CURRENCY = "currency",             --- 货币
    ROLE_EXP = "role_exp",             --- 角色经验物品,
    ABILITY_EXP = "ability_exp",       --- 能力经验物品，
    CHEST = "chest",                   --- 宝箱
    BUFF_CARD = "buff_card",           --- buff卡
    GIFT_PACK = "gift_pack",           --- 礼包
    ABILITY_BOOK = "book",             --- 永久能力激活道具
    AWAKE_CONSUME = "awaken_consume",  --- 能力觉醒消耗物
}

--- 物品类
Define.ITEM_CLASS = {
    [Define.ITEM_TYPE.ABILITY] = require "common.inventory.ability",
    [Define.ITEM_TYPE.BUFF_CARD] = require "common.inventory.item",
    [Define.ITEM_TYPE.GIFT_PACK] = require "common.inventory.item",
    [Define.ITEM_TYPE.ABILITY_BOOK] = require "common.inventory.item",
    [Define.ITEM_TYPE.AWAKE_CONSUME] = require "common.inventory.item",
}

--- 装备槽类型
Define.EQUIPMENT_PART_TYPE = {
    [Define.ITEM_TYPE.ABILITY] = 1,
}

---背包类型
Define.INVENTORY_TYPE = {
    BAG = 1,            --- 道具背包
    EQUIPMENT = 2,      --- 装备背包
    ABILITY = 3,        --- 能力背包
    BODY_PART = 4,      --- 身体槽
}

--- 物品类型与背包类型映射
Define.ITEM_INVENTORY_TYPE = {
    [Define.ITEM_TYPE.ABILITY] = Define.INVENTORY_TYPE.ABILITY,
    [Define.ITEM_TYPE.BUFF_CARD] = Define.INVENTORY_TYPE.BAG,
    [Define.ITEM_TYPE.GIFT_PACK] = Define.INVENTORY_TYPE.BAG,
    [Define.ITEM_TYPE.ABILITY_BOOK] = Define.INVENTORY_TYPE.BAG,
    [Define.ITEM_TYPE.AWAKE_CONSUME] = Define.INVENTORY_TYPE.BAG,
}

--- 背包初始容量
Define.INVENTORY_INIT_CAPACITY = {
    [Define.INVENTORY_TYPE.BAG] = 999,           --- 道具背包
    [Define.INVENTORY_TYPE.EQUIPMENT] = 999,           --- 装备背包
    [Define.INVENTORY_TYPE.ABILITY] = 999,           --- 能力背包
    [Define.INVENTORY_TYPE.BODY_PART] = 999,         --- 身体槽
}

--- 物品品质
Define.ITEM_QUALITY = {
    COMMON = "common",
    RARE = "rare",
    EPIC = "epic",
    LEGENDARY = "legendary",
}

--- 物品品质背景
Define.ITEM_QUALITY_BG = {
    [Define.ITEM_QUALITY.COMMON] = "gameres|asset/imageset/common:img_0_item_white",
    [Define.ITEM_QUALITY.RARE] = "gameres|asset/imageset/common:img_0_item_blue",
    [Define.ITEM_QUALITY.EPIC] = "gameres|asset/imageset/common:img_0_item_purple",
    [Define.ITEM_QUALITY.LEGENDARY] = "gameres|asset/imageset/common:img_0_item_red",
}

--- 品质名称
Define.ITEM_QUALITY_LANG = {
    [Define.ITEM_QUALITY.COMMON] = "g2069_quality_common",
    [Define.ITEM_QUALITY.RARE] = "g2069_quality_rare",
    [Define.ITEM_QUALITY.EPIC] = "g2069_quality_epic",
    [Define.ITEM_QUALITY.LEGENDARY] = "g2069_quality_legendary",
}

--- 物品别称，定义常用物品
Define.ITEM_ALIAS = {
    GOLDEN_CUBE = "gDiamonds",          --- 金魔方
    GOLD_COIN = "gold_coin",            --- 金币
    DEFAULT_ABILITY = "ability_noob",   --- 默认能力
    ROLE_EXP = "role_exp",              --- 角色经验，默认是1点的经验
    ABILITY_EXP = "ability_exp",        --- 能力经验，默认是1点的经验
    AWAKE_CONSUME = "awaken_yu",        --- 觉醒消耗物
}

--- 领奖类型，暂定只做客户端处理
Define.REWARD_TYPE = {
    TASK = 1,             --- 任务领奖
    KILL = 2,             --- 普通击杀奖励
    NPC = 3,              --- NPC对话奖励
    TREASURE_BOX = 4,     --- 打开宝箱
    SHOP_BUY = 5,         --- 商店购买
    LIMITED_TIME = 6,     --- 商业化活动
    GOLDEN_WHEEL = 7,     --- 商业化幸运转盘
    COMBINATION_GIFT = 8, --- 商业化混合礼包
    NPC_LUCKY_DRAW = 9,   --- NPC抽奖
    DROP_ITEM = 10,       --- 丢弃物品
    USE_ITEM = 11,        --- 使用物品
    SUBSCRIBE_VIP = 12,   --- 特权
    MISSION_REWARD = 13,  --- 副本奖励
	BOOK = 14,   		  --- 图鉴奖励
}

--- 伤害类型
Define.DAMAGE_TYPE = {
    PHYSICS = 1,            --- 物理伤害
    ELEMENT = 2,            --- 元素伤害
}

--- 品质字体颜色
Define.ITEM_QUALITY_FONT_COLOR = {
    [Define.ITEM_QUALITY.COMMON] = "FF858997",
    [Define.ITEM_QUALITY.RARE] = "FF43A8FF",
    [Define.ITEM_QUALITY.EPIC] = "FFA640FE",
    [Define.ITEM_QUALITY.LEGENDARY] = "FFFA3F3F",
}

--- 属性字体颜色
Define.ATTR_FONT_COLOR = {
    [Define.ATTR.HEALTH] = "ff9b8f85",
    [Define.ATTR.ATTACK] = "ff9b8f85",
    [Define.ATTR.AGILITY] = "ff9b8f85",
    [Define.ATTR.ENERGY] = "ff9b8f85",
}

Define.DAMAGE_TYPE_ICON = {
    [Define.DAMAGE_TYPE.PHYSICS] = "gameres|asset/imageset/ability:img_0_attack3",
    [Define.DAMAGE_TYPE.ELEMENT] = "gameres|asset/imageset/ability:img_0_agile3",
}

Define.DAMAGE_TYPE_ICON_HOLLOW = {
    [Define.DAMAGE_TYPE.PHYSICS] = "gameres|asset/imageset/ability:img_0_attack2",
    [Define.DAMAGE_TYPE.ELEMENT] = "gameres|asset/imageset/ability:img_0_agile2",
}

Define.DAMAGE_TYPE_NAME = {
    [Define.DAMAGE_TYPE.PHYSICS] = "g2069_damage_type_physics",
    [Define.DAMAGE_TYPE.ELEMENT] = "g2069_damage_type_element",
}

Define.DAMAGE_TYPE_COLOR = {
    [Define.DAMAGE_TYPE.PHYSICS] = "ff9b8f85",
    [Define.DAMAGE_TYPE.ELEMENT] = "ff9b8f85",
}

--- 物品源头
Define.ITEM_REWARD_SOURCE = {
    [Define.REWARD_TYPE.NPC] = "npc",
    [Define.REWARD_TYPE.TREASURE_BOX] = "scene",
    [Define.REWARD_TYPE.SHOP_BUY] = "shop",
    [Define.REWARD_TYPE.TASK] = "task",
    [Define.REWARD_TYPE.KILL] = "kill",
    [Define.REWARD_TYPE.GOLDEN_WHEEL] = "wheel",
    [Define.REWARD_TYPE.COMBINATION_GIFT] = "combinegift",
    [Define.REWARD_TYPE.NPC_LUCKY_DRAW] = "npc_lottery",
    [Define.REWARD_TYPE.DROP_ITEM] = "scene",
    [Define.REWARD_TYPE.USE_ITEM] = "self",
    [Define.REWARD_TYPE.SUBSCRIBE_VIP] = "subscribe_vip",
	[Define.REWARD_TYPE.BOOK] = "book",
    [Define.REWARD_TYPE.MISSION_REWARD] = "mission_get",
}

Define.ABILITY_AWAKE_ICON = {
    [1] = "gameres|asset/imageset/ability:img_0_wake1",
    [2] = "gameres|asset/imageset/ability:img_0_wake2",
    [3] = "gameres|asset/imageset/ability:img_0_wake3",
    [4] = "gameres|asset/imageset/ability:img_0_wake4",
    [5] = "gameres|asset/imageset/ability:img_0_wake5",
    [6] = "gameres|asset/imageset/ability:img_0_wake6",
    [7] = "gameres|asset/imageset/ability:img_0_wake7",
    [8] = "gameres|asset/imageset/ability:img_0_wake8",
    [9] = "gameres|asset/imageset/ability:img_0_wake9",
    [10] = "gameres|asset/imageset/ability:img_0_wake10",
}

--- 皮肤层级
Define.SKIN_LAYER = {
    ORIGINAL = 1,
    ABILITY = 2,
    BUFF = 3,


    COUNT = 3
}

Define.ABILITY_AWAKE_LEVEL = {
    [0] = "N",
    [1] = "Ⅰ",
    [2] = "Ⅱ",
    [3] = "Ⅲ",
    [4] = "Ⅳ",
    [5] = "Ⅴ",
    [6] = "Ⅵ",
    [7] = "Ⅶ",
    [8] = "Ⅷ",
    [9] = "Ⅸ",
    [10] = "Ⅹ",
}

--- gm指令集
Define.GAME_ROLE_COMMON_GM_COMMAND = {
    ADD_ITEM = "add_item",                      --- 添加物品
    ADD_EXP = "add_exp",                        --- 添加经验
    ADD_ABILITY_EXP = "add_ap",                 --- 添加能力经验
    SET_INVINCIBLE = "set_invincible",          --- 设置无敌状态
    RESET_LEVEL = "reset_level",                --- 重置等级
    SHOW_DAMAGE_CALC = "show_damage_calc",      --- 显示伤害计算
    SET_LEVEL = "set_level",                    --- 设置等级
    SET_ABILITY_LEVEL = "set_ability_level",    --- 设置能力等级
    CLEAR_DATA = "clear_data",                  --- 清空数据
    ADD_BUFF = "add_buff",                      --- 添加buff
    GO_TO_MAP = "go_to_map",                    --- 前往地图
    SET_DANGER_VALUE = "set_danger_value",      --- 设置危险值
    SET_ABILITY_AWAKE = "set_ability_awake",    --- 设置能力觉醒
}

Define.DEFAULT_SKIN_COLOR = { 1, 1, 1, 0 }
Define.EMPTY_SKIN_COLOR = { 0, 0, 0, 0 }