---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 江奕铭.
--- DateTime: 2021/2/4 14:28
--- 一个简易的飘字插件
--- 在游戏assert目录下配置setting.json
--- 详情见 https://www.tapd.cn/38329646/markdown_wikis/show/#1138329646001000421
---

require "helper.fly_text_helper"
if World.isClient then
    require "gm_fly_text"
end

---@type FlyTextHelper
local FlyTextHelper = T(Lib, "FlyTextHelper")

local handlers = {}

function handlers.onShowWorldFlyText(entity, atlas, text, scale)
    FlyTextHelper:onShowEntityFlyText(entity, atlas, text, scale)
end

function handlers.onShowUIFlyText(entity, atlas, text, scale)
    -- 需要是图集
    FlyTextHelper:onShowUIFlyText(entity, atlas, text, scale)
end

function handlers.onEntityShowFlyText(entity, textType, text)
    FlyTextHelper:onShowEntityFlyText(entity, textType.color, text, textType.scale)
end

return function(name, ...)
    if type(handlers[name]) ~= "function" then
        return
    end
    handlers[name](...)
end