---
--- Generated by PluginCreator
--- game_common handler
--- DateTime:2023-02-24
---

local handles = T(Player, "PackageHandlers")
--function handles:Xxxxx(packet)
--end

function handles:RequestGMUpdateSkillBuff(packet)
    if not World.cfg.openGM then
        return
    end
    self:updateSkillBuffById(packet.buffId, packet.isAdd)
end

---objID,isIncludeSelf ,soundKey
function handles:broadcastSound(packet)
    local entity=World.CurWorld:getEntity(packet.objID)
    if not entity or not entity:isValid() then
        return
    end
    self:sendPacketToTracking({pid="PushClientPlaySound",objID=packet.objID,soundKey=packet.soundKey}, packet.includeSelf)
end

function handles:RequestGMNPCLuckyDraw(packet)
    if not World.cfg.openGM then
        return
    end
    ---@type NpcRewardSettingConfig
    local NpcRewardSettingConfig = T(Config, "NpcRewardSettingConfig")
    local rewardCfg = NpcRewardSettingConfig:getCfgByPoolId(packet.poolId)
    if rewardCfg then
        for i = 1, 1000 do
            self:doNpcLuckyDraw(rewardCfg.poolGroup, packet.poolId, rewardCfg.item_alias, 0)
        end
    end
end
