---
--- Generated by PluginCreator
--- game_common player
--- DateTime:2023-02-24
---

local Player = Player

function Player:doPlaySceneEffect(effectInfo)
    local packet = {
        pid = "PushClientPlaySceneEffect",
        action = effectInfo.action,
        scale = effectInfo.scale,
        effectName = effectInfo.effectName,
        pos = effectInfo.pos,
        yaw = effectInfo.yaw or 0,
        time = effectInfo.time,
        sound=effectInfo.sound,
        objID=effectInfo.objID
    }
    self:sendPacketToTracking(packet, effectInfo.includeSelf)
end

function Player:pushClientShowTips(text)
    local packet = {
        pid = "PushClientShowTips",
        text = text
    }
    self:sendPacket(packet)
end

function Player:updateSafeBuffShow()
    --local safeModeType = self:getSafeModeType()
    --if safeModeType == Define.PKModeType.safe or safeModeType == Define.PKModeType.pkWait then
    --    self:addBuff("myplugin/safe_model_buff")
    --elseif safeModeType == Define.PKModeType.pk1 then
    --    if self:isInSafeRegion() then
    --        self:addBuff("myplugin/safe_model_buff")
    --    else
    --        self:removeTypeBuff("fullName", "myplugin/safe_model_buff")
    --    end
    --else
    --    self:removeTypeBuff("fullName", "myplugin/safe_model_buff")
    --end
end