---
--- Generated by PluginCreator
--- task_system entity_func
--- DateTime:2023-03-23
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
---@type TaskConfig
local TaskConfig = T(Config, "TaskConfig")

function Entity.ValueFunc:mainTask(value)
    Lib.emitEvent(Event.EVENT_TASK_UPDATE_MY_TASK, Define.TaskType.Main)
    if not self.firstLoginMainTask then
        for taskId, val in pairs(value or {}) do
            local taskConfig = TaskConfig:getCfgById(taskId)
            if taskConfig.guideMap ~= "" and taskConfig.autoGuide then
                Lib.emitEvent(Event.EVENT_TASK_UPDATE_GUIDE_SHOW, taskId)
            end
        end
        self.firstLoginMainTask = true
    end
end

function Entity.ValueFunc:branchTask(value)
    Lib.emitEvent(Event.EVENT_TASK_UPDATE_MY_TASK, Define.TaskType.Branch)
    if not self.firstLoginBranchTask then
        for taskId, val in pairs(value or {}) do
            local taskConfig = TaskConfig:getCfgById(taskId)
            if taskConfig.guideMap ~= "" and taskConfig.autoGuide then
                Lib.emitEvent(Event.EVENT_TASK_UPDATE_GUIDE_SHOW, taskId)
            end
        end
        self.firstLoginBranchTask = true
    end
end