---
--- Generated by PluginCreator
--- game_time 's gate
--- DateTime:2021-11-26
--- @class GameTimeClient
local GameTimeClient = T(Lib, "GameTimeClient")
--function GameTimeClient:export_getXXX()
	-----TODO
--end

--function GameTimeClient:import_getXXX()
	-----TODO
--end
return GameTimeClient
