---
--- Generated by PluginCreator
--- game_book entity
--- DateTime:2023-06-19
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
