---
--- Generated by PluginCreator
--- new_chat entity
--- DateTime:2022-01-06
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
