---
--- Generated by PluginCreator
--- game_coin entity
--- DateTime:2023-02-03
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
