---
--- Generated by PluginCreator
--- fly_new_tips handler
--- DateTime:2023-04-17
---

local handles = T(Player, "PackageHandlers")
---@type FlyNewTipsHelper
local FlyNewTipsHelper = T(Lib, "FlyNewTipsHelper")

function handles:SyncClientShowOneFlyTips(packet)
    FlyNewTipsHelper:pushOneFlyNewTipsItem(packet.itemInfo)
end
