---
--- Generated by PluginCreator
--- engine_overwrite player
--- DateTime:2023-02-24
---

local Player = Player

local oldLoadDBData = Player.loadDBData
function Player:loadDBData(data)
    oldLoadDBData(self, data)
    ---加载游戏自定义数据
    self:setDBData(data)
end
