---
--- Generated by PluginCreator
--- scene_object handler
--- DateTime:2023-03-23
---
---@type MapManagerServer
local MapManagerServer = require "server.manager.game_map_manager"
---@type PlayerDataHelper
local PlayerDataHelper = T(Lib, "PlayerDataHelper")

local handles = T(Player, "PackageHandlers")
--function handles:Xxxxx(packet)
--end

--- 传送等待
---@param packet any
function handles:C2STeleportWait(packet)
    ---@type Entity
    local player = self
    player:enterStateType(Define.RoleStatus.IN_TELEPORT)
end

--- 传送
---@param packet any
function handles:C2STeleportMap(packet)
    ---@type Entity
    local player = self
    local mapName = packet.map
    local toTeleportId = packet.tid
    local position = packet.pos
    local setBorn = packet.setBorn
    local stateCode = 0
    if setBorn and setBorn == 1 then
        player:setBornMap(mapName)
        PlayerDataHelper:saveDataImmediate(player)
        player:checkUpdateTaskData(Define.TargetConditionKey.BORN)
        Lib.emitEvent(Event.EVENT_SCENE_OBJECT_SET_BORN_MAP, player, mapName)
    end

    if player:isInMissionRoom() then
        stateCode = 3
    else
        if toTeleportId then
            if MapManagerServer:instance():gotoMapTeleport(player, mapName, toTeleportId) then
    
            else
                stateCode = 1
            end
        else
            if position then
                position = Vector3.new(position.x, position.y, position.z)
            end
            if MapManagerServer:instance():gotoMap(player, mapName, position) then
    
            else
                stateCode = 2
            end
        end
    end
    --- 退出状态
    player:exitStateType(Define.RoleStatus.IN_TELEPORT)
    return stateCode
end
