---
--- Generated by PluginCreator
--- jump_control gm
--- DateTime:2023-03-03
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
--GMItem["jump_control/一个彩蛋"] = function()
--end
