---
--- Generated by PluginCreator
--- game_common entity
--- DateTime:2023-02-24
---

local Entity = Entity
local EntityClient = EntityClient

-- 这里是直接改变entity实例的属性，也就是self:getEntityProp(prop)的值，self:prop().prop值是不会变的
-- 所以改完可以回复成self:prop().prop值
--   self:setProp 改变的是 self:prop().prop和entity实例的值
--function Entity:setEntityProp(prop, value)
--    --self:recoverEntityProp(prop)
--    local curValue = tonumber(self:getEntityProp(prop))
--    self:deltaEntityProp(prop, -curValue + tonumber(value))
--end

--function Entity:resetEntityProp(prop)
--    self:setProp(prop, self:prop()[prop])
--end

function Entity:showPkModeEnterWaitTime()
    local args = {
        position = Vector3.new(0, World.cfg.pkWaitEnter.offsetY, 0),
        width = World.cfg.pkWaitEnter.waitWinWidth,
        height = World.cfg.pkWaitEnter.waitWinHeight,
        objID = self.objID,
        flags = 4
    }
    local sceneWindow, headPkInstance
    headPkInstance = self.headPkInstance
    if not headPkInstance then
        sceneWindow, headPkInstance = UI:openSceneWindow("UI/main/gui/win_enter_pk_wait",
                "win_enter_pk_wait"..self.objID, args,
                "asset",
                self.objID)
        self.headPkInstance = headPkInstance
    end
end