---
--- Generated by PluginCreator
--- game_common entity_func
--- DateTime:2023-02-24
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")

---@type ActionMapHelper
local ActionMapHelper = T(Lib, "ActionMapHelper")

function Entity.ValueFunc:actionMappingData(value)
    ActionMapHelper:resetPlayMapAction(self)
    if self.objID==Me.objID then
        --print("===================== Entity.ValueFunc actionMappingData",Lib.v2s(value.isInBattleState))
        Me:setCalcYawBySpeedDir(value.isInBattleState and 0 or 1,Define.CalcYawPriority.BattleStateLimit)
        Me:setPlayerBodyRotation(value.isInBattleState,Define.BodyRotationPriority.BattleStateLimit)
    end
end

function Entity.ValueFunc:safeModeType(value, oldValue)
    if self.objID == Me.objID then
        Lib.emitEvent(Event.EVENT_SAFE_MODE_UPDATE, value)
        if value == Define.PKModeType.safe then
            Plugins.CallTargetPluginFunc("fly_new_tips", "pushFlyNewTipsText", "g2069_auto_open_safe_mode_tips")
        end
    end
    if value == Define.PKModeType.pkWait then
        self:showPkModeEnterWaitTime()
    end
    if self.isPlayer then
        self:updateShowName()
    end
end

function Entity.ValueFunc:skillOpenShake(value)
    if self.objID==Me.objID then
        Lib.emitEvent(Event.EVENT_SKILL_OPEN_SHAKE_UPDATE)
    end
end