---
--- Generated by PluginCreator
--- game_business player
--- DateTime:2023-04-10
---

local Player = Player
---@type ShopConfig
local ShopConfig = T(Config, "ShopConfig")
---@type WalletSystem
local WalletSystem = T(Lib, "WalletSystem")
---@type ItemConfig
local ItemConfig = T(Config, "ItemConfig")

function Player:clientBuyShopByShopId(shopId)
    if not shopId then
        return
    end
    local cost = ShopConfig:getCfgByShopId(shopId).cost
    local coinName = cost.item_alias
    local coinNum = cost.item_num
    local myCoin = WalletSystem:getCoin(Me, coinName)
    if myCoin < coinNum then
        local name = ItemConfig:getName(coinName)
        Me:showGameTopTips(Lang:toText({ "g2069_not_enough_coin", name }))
        if coinName == Define.ITEM_ALIAS.GOLDEN_CUBE then
            Interface.onRecharge(1)
        end
        return
    end

    Me:sendPacket({
        pid = "C2SShopBuy",
        shopId = shopId,
    })
    return true
end
