---
--- Generated by PluginCreator
--- fly_new_tips gm
--- DateTime:2023-04-17
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
--GMItem["fly_new_tips/一个彩蛋"] = function()
--end
