---
--- Generated by PluginCreator
--- task_system gm
--- DateTime:2023-03-23
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
--GMItem["任务/更新UI"] = function()
--    Lib.emitEvent(Event.EVENT_TASK_UPDATE_MY_TASK)
--end

GMItem["任务/打印主任务"] = function(self)
    if not World.cfg.openGM then
        return
    end
    local mainTask = Me:getMainTask()
    print("wwww mainTask", Lib.v2s(mainTask,5))
end

GMItem["任务/打印支线任务"] = function(self)
    if not World.cfg.openGM then
        return
    end
    local branchTask = Me:getBranchTask()
    print("wwww branchTask", Lib.v2s(branchTask,5))
end

GMItem["任务/打印已完成任务"] = function(self)
    if not World.cfg.openGM then
        return
    end
    local completeTask = Me:getCompleteTask()
    print("wwww completeTask", Lib.v2s(completeTask,5))
end

GMItem["任务/对话数据"] = function(self)
    if not World.cfg.openGM then
        return
    end
    local DialogRecord = Me:getDialogRecord()
    print("DialogRecord", Lib.v2s(DialogRecord,5))
end