---
--- Generated by PluginCreator
--- role_state_manager entity_func
--- DateTime:2023-03-13
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
--function Entity.ValueFunc:xxx(value)
--    Lib.emitEvent(Event.xxx,1,value)
--end
