---
--- Generated by PluginCreator
--- player_action player
--- DateTime:2023-05-09
---

local Player = Player
function Player:stopPlayerAction(packet)
    self:sendPacketToTracking({pid="S2CStopPlayerAction",objID=self.objID}, true)
end
