---
--- Generated by PluginCreator
--- new_limited_time_activity handler
--- DateTime:2023-04-17
---

---@type LimitedTimeActivityConfig
local LimitedTimeActivityConfig = T(Config, "LimitedTimeActivityConfig")
local handles = T(Player, "PackageHandlers")
--function handles:Xxxxx(packet)
--end

function handles:PlayLimitedTimeGoldWheel(packet)
    local params = packet.params
    if not params or not params.id then
        return
    end
    local item = LimitedTimeActivityConfig:getCfgById(params.id)
    if item and item.type == Define.LIMITED_TIME_ACTIVITY_TYPE.LIMITED_TIME_GOLD_WHEEL then
        Plugins.CallTargetPluginFunc("new_game_report", "playLimitedTimeGoldWheel", self, params.id)
        LimitedTimeActivityMgr:playActivity(self, item)
    end
end
