---
--- Generated by PluginCreator
--- party_game entity_common
--- DateTime:2022-05-13
---

local Entity = Entity

function Entity:noticePlaySound(soundKey)
    if not self.isPlayer then
        return
    end
    self:sendPacket({
        pid = "NoticePlaySound",
        soundKey = soundKey,
    })
end