---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/12/30 14:34
---
---@class BaseSkill
local BaseSkill = T(Skill, "BaseSkill")

function BaseSkill:doSkillHitResult(freeEntity, skill, target)

end

return BaseSkill