---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/12/30 14:34
---
---@class JumpSkill
local JumpSkill = T(Skill, "JumpSkill")

function JumpSkill:doSkillHitResult(freeEntity, skill, target)
end

return JumpSkill