---
--- Generated by PluginCreator
--- g2060_friend handler
--- DateTime:2022-07-07
---
local FriendSpecialData = T(Lib, "FriendSpecialData")

local handles = T(Player, "PackageHandlers")

function handles:C2SGetSpecialDataList(packet)
    FriendSpecialData:getSpecialData(packet.userIds, self.platformUserId)
end

function handles:C2SPlayerFollow(packet)
    self:onPlayerFollow(packet)
end