---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/4/11 17:58
---

local RoleStateBase = require "common.state.base_state"

--- @class RoleStateFreeze : RoleStateBase
local RoleStateFreeze = Lib.class("RoleStateFreeze", RoleStateBase)

function RoleStateFreeze:init(type)
    RoleStateBase.init(self, type or Define.RoleStatus.FREEZE)
end

function RoleStateFreeze:enterState(objID)
    RoleStateBase.enterState(self, objID)
    if World.isClient then
        if objID == Me.objID then
            Me:updateDisableControlCounts(1)
        end
    end
end

function RoleStateFreeze:exitState(objID)
    RoleStateBase.exitState(self, objID)
    if World.isClient then
        if objID == Me.objID then
            Me:updateDisableControlCounts(-1)
        end
    end
end

return RoleStateFreeze