---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/4/11 17:57
---

local RoleStateBase = require "common.state.base_state"

--- @class RoleStateVertigo : RoleStateBase
local RoleStateVertigo = Lib.class("RoleStateVertigo", RoleStateBase)

function RoleStateVertigo:init(type)
    RoleStateBase.init(self, type or Define.RoleStatus.VERTIGO)
end

function RoleStateVertigo:enterState(objID)
    RoleStateBase.enterState(self, objID)
    if World.isClient then
        if objID == Me.objID then
            Me:updateDisableControlCounts(1)
        end
    end
end

function RoleStateVertigo:exitState(objID)
    RoleStateBase.exitState(self, objID)
    if World.isClient then
        if objID == Me.objID then
            Me:updateDisableControlCounts(-1)
        end
    end
end

return RoleStateVertigo