---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/3/13 11:18
---

local RoleStateBase = require "common.state.base_state"

--- @class RoleBattlePreState : RoleStateBase
local RoleBattlePreState = Lib.class("RoleBattlePreState", RoleStateBase)

function RoleBattlePreState:init(type)
    RoleStateBase.init(self, type or Define.RoleStatus.BATTLE_PRE)
end

function RoleBattlePreState:enterState(objID)
    RoleStateBase.enterState(self, objID)
    --if not World.isClient then
    --    local entity = World.CurWorld:getEntity(objID)
    --    if entity and entity:isValid() then
    --        entity:addBuff("myplugin/battle_idle_buff")
    --    end
    --end
end

function RoleBattlePreState:exitState(objID)
    RoleStateBase.exitState(self, objID)
    --if not World.isClient then
    --    local entity = World.CurWorld:getEntity(objID)
    --    if entity and entity:isValid() then
    --        entity:addBuff("myplugin/normal_idle_buff")
    --    end
    --end
end

return RoleBattlePreState