---
--- Generated by PluginCreator
--- g2060_friend define
--- DateTime:2022-07-07
---

Define.FriendTagMainType = {
    Friend = 1,
    Nearby = 2
}

Define.FriendTagSubType = {
    Friends = 1,
    Invite = 2,
    PeopleNearby = 3
}

Define.FriendGameStatus = {
    Other = 0,
    Hall = 1,
    PartyGame = 2
}

