---
--- Generated by PluginCreator
--- g2060_friend entity_common
--- DateTime:2022-07-07
---

local ValueDef = T(Entity, "ValueDef")
-- key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
ValueDef.lastFollowTime 		= {false,   false,  true,   false,      0,                     false}
ValueDef.followData 		    = {false,   false,  true,   false,      {},                    true}

local Entity = Entity

function Entity:getLastFollowTime()
    return self:getValue("lastFollowTime")
end

function Entity:setLastFollowTime()
    local time = os.time() + World.cfg.g2060_friendSetting.followCd
    self:setValue("lastFollowTime", time)
end

function Entity:clearLastFollowTime()
    self:setValue("lastFollowTime", 0)
end

function Entity:getFollowData()
    return self:getValue("followData")
end

function Entity:setFollowData(followData)
    self:setValue("followData", followData)
end