---
--- Generated by PluginCreator
--- g2060_friend event
--- DateTime:2022-07-07
---

if World.isClient then
    Event.EVENT_G2060_FRIEND_GET_SPECIAL_DATA = Event.register("EVENT_G2060_FRIEND_GET_SPECIAL_DATA")
    Event.EVENT_G2060_FRIEND_MY_LIVE_CHANGE = Event.register("EVENT_G2060_FRIEND_MY_LIVE_CHANGE")
else

end
