---
--- Generated by PluginCreator
--- g2060_friend entity
--- DateTime:2022-07-07
---

local Entity = Entity
local EntityServer = EntityServer
--buff key:
--function Entity.EntityProp:xxx(value, add, buff)
--end
