---
--- Generated by PluginCreator
--- game_mission handler
--- DateTime:2023-06-14
---

local handles = T(Player, "PackageHandlers")

---@type GameMissionGMHelperServer
local GameMissionGMHelperServer = T(Lib, "GameMissionGMHelperServer")

--- 副本等待
---@param packet any
function handles:C2SEnterMissionWait(packet)
    ---@type Entity
    local player = self
    player:enterStateType(Define.RoleStatus.IN_TELEPORT)
end

--- 进入副本
---@param packet any
function handles:C2SEnterMission(packet)
    ---@type Entity
    local player = self
    local roomId = packet.roomId
    local stateCode = 0
    ---@type MissionManagerServer
    local MissionManagerServer = require "server.manager.mission_manager"
    if MissionManagerServer:instance():joinRoom(player, roomId) then
        --- 添加数据
    else
        stateCode = 1
    end
    --- 退出状态
    player:exitStateType(Define.RoleStatus.IN_TELEPORT)
    player:sendPacket({
        pid = "S2CEnterMission",
        stateCode = stateCode,
        roomId = roomId,
    })
    return stateCode
end

function handles:C2SMissionTeammateCanSelect(packet)
    self:checkCanSelectMissionTeammate(packet.missionId)
end

function handles:C2SMissionOpenMissionTeleport(packet)
    self:doOpenMissionTeleport(packet.missionMode, packet.missionId, packet.selectUserList)
end

---重置副本次数
function handles:C2SGMResetMissionCounts(packet)
    if not World.cfg.openGM then
        return
    end
    self:resetMissionCountInfo()
end
