---
--- Generated by PluginCreator
--- game_role_common gm
--- DateTime:2023-03-03
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_server.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_server")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
---@type GameRoleCommonGMHelperServer
local GameRoleCommonGMHelperServer = T(Lib, "GameRoleCommonGMHelperServer")
---@type ItemConfig
local ItemConfig = T(Config, "ItemConfig")

--GMItem["game_role_common/一个彩蛋"] = function()
--end

GMItem["角色通用/添加经验"] = GM:inputNumber(function(self, exp)
    exp = exp or 100
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.ADD_EXP,
        exp = exp
    })
end)

GMItem["角色通用/添加能力经验"] = GM:inputNumber(function(self, exp)
    exp = exp or 100
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.ADD_ABILITY_EXP,
        exp = exp
    })
end)

GMItem["角色通用/开启无敌"] = function(self)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SET_INVINCIBLE,
        enable = true,
    })
end

GMItem["角色通用/关闭无敌"] = function(self)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SET_INVINCIBLE,
        enable = false,
    })
end

GMItem["角色通用/重置等级"] = function(self)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.RESET_LEVEL,
    })
end

GMItem["角色通用/打开伤害公式"] = function(self)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SHOW_DAMAGE_CALC,
        enable = true,
    })
end

GMItem["角色通用/关闭伤害公式"] = function(self)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SHOW_DAMAGE_CALC,
        enable = false,
    })
end

GMItem["角色通用/设置等级"] = GM:inputNumber(function(self, level)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SET_LEVEL,
        level = level,
    })
end)

GMItem["角色通用/设置能力等级"] = GM:inputNumber(function(self, level)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SET_ABILITY_LEVEL,
        level = level,
    })
end)

GMItem["角色通用/清除数据"] = function(self)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.CLEAR_DATA,
    })
end

GMItem["角色通用/添加能力"] = GM:inputNumber(function(self, abilityId)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.ADD_ITEM,
        item_id = abilityId,
        item_num = 1,
    })
end)

GMItem["角色通用/添加Buff"] = GM:inputNumber(function(self, buffId)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.ADD_BUFF,
        buffId = buffId,
    })
end)

GMItem["角色通用/前往地图"] = GM:inputStr(function(self, mapName)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.GO_TO_MAP,
        map = mapName,
    })
end)

GMItem["角色通用/设置危险指数"] = GM:inputNumber(function(self, value)
    GameRoleCommonGMHelperServer:onCommandHandle(self, {
        command = Define.GAME_ROLE_COMMON_GM_COMMAND.SET_DANGER_VALUE,
        exp = value,
    })
end)

-- GMItem["角色通用/添加勾玉"] = GM:inputNumber(function(self, value)
--     GameRoleCommonGMHelperServer:onCommandHandle(self, {
--         command = Define.GAME_ROLE_COMMON_GM_COMMAND.ADD_ITEM,
--         item_alias = Define.ITEM_ALIAS.AWAKE_CONSUME,
--         item_num = value or 100,
--     })
-- end)
