---
--- Generated by PluginCreator
--- task_system event
--- DateTime:2023-03-23
---

if World.isClient then
    Event.EVENT_TASK_UPDATE_MY_TASK = Event.register("EVENT_TASK_UPDATE_MY_TASK")
    Event.EVENT_TASK_UPDATE_GUIDE_SHOW = Event.register("EVENT_TASK_UPDATE_GUIDE_SHOW")

    Event.EVENT_TASK_UI_UPDATE_TASK = Event.register("EVENT_TASK_UI_UPDATE_TASK")
else

end
