---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/26 17:59
---

Lib.subscribeEvent(Event.EVENT_FRIEND_OPERATION_NOTICE, function(operationType, playerPlatformId)
    --for the gear
    local opType = FriendManager.operationType
    if operationType == opType.AGREE then
        operationType = 3
    elseif operationType == opType.ADD_FRIEND then
        operationType = 4
    elseif operationType == opType.REFUSE then
        operationType = 5
    end
    if type(operationType) == "number" then
        Lib.emitEvent(Event.EVENT_FRIEND_OPERATION_FOR_SERVER, operationType, playerPlatformId)
    end
end)

Lib.subscribeEvent(Event.EVENT_FRIEND_OPERATION_FOR_SERVER, function(operationType, playerPlatformId)
    if operationType == 3 then
        FriendManager.friendsMap[playerPlatformId] = true
        local playerInfo = Game.GetPlayerByUserId(playerPlatformId)
        if playerInfo then
            local text = Lang:toText({"g2060_agree_add_friend", playerInfo.name})
            Me:showGameTopTips(text)
        end
        Me:addPlayerFriendFromExist(playerPlatformId)
    end

    if operationType == 4 then
        if not FriendManager.CanAddFriend(playerPlatformId) then
            return
        end
        local playerInfo = Game.GetPlayerByUserId(playerPlatformId)
        if playerInfo then
            local text = Lang:toText({"g2060_request_add_friend", playerInfo.name})
            Me:showGameTopTips(text)
        end
    end

    --拒绝不用通知对方
    if operationType == 5 then
        local playerInfo = Game.GetPlayerByUserId(playerPlatformId)
        if playerInfo then
            local text = Lang:toText({"g2060_refuse_add_friend", playerInfo.name})
            Me:showGameTopTips(text)
        end
    end
end)

Lib.subscribeEvent(Event.EVENT_FRIEND_OPERATION_CLIENT, function(operationType, userId)
    local oType = FriendManager.operationType
    if operationType == oType.AGREE then
        --AGREE_ADD_FRIEND
        Me:sendPacket({
            pid = "SendFriendOperation",
            operationType = operationType,
            userId = userId
        })
        Me:showGameTopTips(Lang:toText("g2060_friend_agree_friend_invite"))
    elseif operationType == oType.REFUSE then
        --REQUEST_ADD_FRIEND
        Me:sendPacket({
            pid = "SendFriendOperation",
            operationType = operationType,
            userId = userId
        })
        Me:showGameTopTips(Lang:toText("g2060_friend_refuse_friend_invite"))
    elseif operationType == oType.DELETE then
        Me:showGameTopTips(Lang:toText("g2060_friend_delete_friend_tips"))
    end
end)