---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/11 15:30
---

local FriendSpecialData = T(Lib, "FriendSpecialData")

function FriendSpecialData:init()
    self.dataDict = {}
    self.friendOnlineStatus = {}
end

function FriendSpecialData:setClientSpecialData(dataList)
    for i, v in pairs(dataList) do
        self.dataDict[v.userId] = v.specialData
    end
end

function FriendSpecialData:getClientSpecialData(userId)
    return self.dataDict[userId]
end

--暂时不用 friendOnlineStatus
function FriendSpecialData:getFriendOnlineState(userId)
    return self.friendOnlineStatus[userId] or Define.onlineStatus.offline
end

function FriendSpecialData:requestFriendOnlineState(userIds)
    if #userIds > 0 then
        local callFunc = function(data)
            for _, onlineData in pairs(data) do
                self.friendOnlineStatus[onlineData.userId] = onlineData.status
            end
            Lib.emitEvent(Event.EVENT_UPDATE_ONLINE_STATE_SHOW)
        end
        AsyncProcess.GetPlayerOnlineState(userIds, callFunc)
    end
end


FriendSpecialData:init()

return FriendSpecialData