---
--- Generated by PluginCreator
--- g2060_friend gm
--- DateTime:2022-07-07
---

local path = Root.Instance():getGamePath():gsub("\\", "/") .. "lua/gm_client.lua"
local file, err = io.open(path, "r")
local GMItem
if file then
    GMItem = require("gm_client")
    file:close()
end
if not GMItem then
    GMItem = GM:createGMItem()
end
GMItem["g2060_friend/Get special data of friends"] = function(self)
    if not World.cfg.openGM then
        return
    end
    self:sendPacket({
        pid = "C2SGetSpecialDataList"
    })
end