---
--- Generated by PluginCreator
--- game_mission entity_common
--- DateTime:2023-06-14
---

---@type MissionInfoConfig
local MissionInfoConfig = T(Config, "MissionInfoConfig")

local ValueDef = T(Entity, "ValueDef")
-- key				            = {isCpp,	client,	toSelf,	toOther,	init,	               saveDB}
--ValueDef.xxx 					= {false,   false,  true,   false,      0,                      true}
ValueDef.missionRoomData 		= {false,   false,  true,   false,      {},                      false}
ValueDef.missionMonsterData     = {false,   false,  false,   true,      {},                      false}     --- 怪物专用数据
ValueDef.missionStateData       = {false,   false,  true,   false,      {},                      false}     --- 房间状态数据

local Entity = Entity

function Entity:setMissionRoomData(value)
    self:setValue("missionRoomData", value)
end

function Entity:getMissionRoomData()
    return self:getValue("missionRoomData")
end

function Entity:setMissionStateData(value)
    self:setValue("missionStateData", value)
end

function Entity:getMissionStateData()
    return self:getValue("missionStateData")
end

--- 清空指定房间数据
---@param roomId string
function Entity:clearMissionRoomData(roomId)
    local data = self:getMissionRoomData()
    if data and data.roomId and (not roomId or roomId == data.roomId) then
        self:setMissionRoomData({})
        self:setMissionStateData({})
    end
end

--- 判断是否在副本中
---@param roomId string 判断是否在指定房间中，不传则不做指定判断
function Entity:isInMissionRoom(roomId)
    local data = nil
    if self.isPlayer then
        data = self:getMissionRoomData()
    elseif self:isMonster() then
        data = self:getMissionMonsterData()
    end
    if data and data.enter and data.roomId and (not roomId or roomId == data.roomId) then
        return true
    end
    return false
end

--- 判断是否开启
---@param missionGroup number 任务组
function Entity:isMissionGateOpen(missionGroup)
    local data = self:getMissionRoomData()
    if data and data.missionId and not data.enter then
        local missionId = data.missionId
        if MissionInfoConfig:getCfgByMissionId(missionId).mission_group == missionGroup then
            return true
        end
    end
    return false
end

--- 获取副本id
function Entity:getMissionRoomId()
    local data = self:getMissionRoomData()
    if data and data.roomId then
        return data.roomId
    end
    return nil
end

--- 获取任务组
function Entity:getMissionRoomGroup()
    local data = self:getMissionRoomData()
    if data and data.missionId then
        return MissionInfoConfig:getCfgByMissionId(data.missionId).mission_group
    end
    return nil
end

-- 玩家是否已经被邀请了进入觉醒副本（还没进入传送阵）
function Entity:isInMissionPreState()
    local data = self:getMissionRoomData()
    if data and data.roomId and not data.enter then
        return true
    end
    return false
end

--- 判断是否能开启
---@param missionId any
function Entity:canOpenMission(missionId)
    if self:isInMissionRoom() or self:isInMissionPreState() then
        return false
    end
    return true
end

--- 是否副本怪物
function Entity:isMissionMonster()
    if self:isMonster() then
        return self:isInMissionRoom()
    end
    return false
end

function Entity:setMissionMonsterData(value)
    self:setValue("missionMonsterData", value)
end

function Entity:getMissionMonsterData()
    return self:getValue("missionMonsterData")
end