---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/4/23 15:06
---
local class = require "common.class"

local JumpState = require "client.player.state.jump_state"
local JumpFloatState = class("JumpFloatState", JumpState)

function JumpFloatState:enter(owner)
    if owner.jumpRaiseEnd then
        return
    end

    owner.jumpRaiseEnd = true
    owner.jumpRealHeight = owner:curBlockPos().y - owner.startJumpPosy

    local jumpCount = owner:getJumpCount()
    local maxJumpCount = owner:getMaxJumpCount()

    if jumpCount >= 0 then
        ---滞空
        ---@type LuaTimer
        --local LuaTimer = T(Lib, "LuaTimer")
        --LuaTimer:cancel(owner.jumpFloatTimer)
        --owner.jumpFloatTimer = LuaTimer:scheduleTimer(function()
        --    owner:changeJumpState("JumpFreeFallState")
        --end, World.cfg.jump_controlSetting.floatTime, 1)

        owner:changeJumpState("JumpFreeFallState")
    else
        owner:changeJumpState("JumpFreeFallState")
    end
end

function JumpFloatState:update(owner)
end

function JumpFloatState:leave(owner)
    ---@type LuaTimer
    local LuaTimer = T(Lib, "LuaTimer")
    LuaTimer:cancel(owner.jumpFloatTimer)
end

return JumpFloatState