---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangpq.
--- DateTime: 2020/4/23 14:52
---
local class = require "common.class"

local JumpState = class("JumpState")

function JumpState:ctor()
    --self.owner = owner
end

function JumpState:enter(owner)
    --TODO
end

function JumpState:update(owner)
    --TODO
end

function JumpState:leave(owner)
    --TODO
end

return JumpState