---
--- Generated by PluginCreator
--- monster_manager define
--- DateTime:2023-03-01
---


-- 怪物类型
Define.MonsterType = {
    SMALL_MONSTER = 1,                  -- 小怪
    HEIGHT_MONSTER = 2,                 -- 高级怪
    BOSS = 3,                           -- boss
    MISSION = 4,                           -- 副本怪
}
