---
--- Generated by PluginCreator
--- new_limited_time_activity entity_func
--- DateTime:2023-04-17
---

local Entity = Entity
local ValueFunc = T(Entity, "ValueFunc")
--function Entity.ValueFunc:xxx(value)
--    Lib.emitEvent(Event.xxx,1,value)
--end

function Entity.ValueFunc:limitedTimeWeekKey(value)

end

function Entity.ValueFunc:limitedTimeMonthKey(value)
    
end
