---
--- Generated by PluginCreator
--- scene_object define
--- DateTime:2023-03-23
---

--Define.XXX_XX_X = 0.2 


Define.SCENE_OBJECT_COLLISION_GROUP = {
    NONE = "64",
    DEFAULT = "8",
    [Define.ITEM_TYPE.ABILITY] = "8",
    CHEST = "8",
    BROKEN_OBJECT = "256",
}