---
--- Generated by PluginCreator
--- game_common handler
--- DateTime:2023-02-24
---

local handles = T(Player, "PackageHandlers")
--- @type SoundManager
local SoundManager = T(Lib, "SoundManager")

function handles:PushClientPlaySceneEffect(packet)
    self:clientDoPlaySceneEffect(packet)
end

function handles:PushClientShowTips(packet)
    Me:showGameTopTips(Lang:toText(packet.text))
end

function handles:PushClientPlaySound(packet)
    --print("+++++++++++++++++++++ handles:PushClientPlaySound",packet.objID,packet.soundKey)
    local entity=World.CurWorld:getEntity(packet.objID)
    if not entity or not entity:isValid() then
        return
    end
    SoundManager:playSound(packet.soundKey,entity)
end

