---
--- Generated by PluginCreator
--- camera_edit mainLua
--- DateTime:2023-05-25
---
require "common.util_camera_edit"
require "common.entity_camera_edit"
require "common.event_camera_edit"
require "common.config.scene_welcome_config"
require "common.define_camera_edit"
if World.isClient then
    require "client.player.player_camera_edit"
    require "client.player.packet_camera_edit"
    require "client.entity.entity_camera_edit"
    require "client.entity.entity_value_func_camera_edit"
    require "client.gm_camera_edit"
else
    require "server.player.player_camera_edit"
    require "server.player.packet_camera_edit"
    require "server.entity.entity_camera_edit"
    require "server.gm_camera_edit"
end

local handlers = {}

--function handlers.openXXXWnd()
	--TODO
--end

return function(name, ...)
	if type(handlers[name]) ~= "function" then
		return
	end
	return handlers[name](...)
end
